version: 2.1

# Shared reference for a environment
executors:
  default:
    docker:
      - image: circleci/node:10.9
    environment:
      # CODECOV_TOKEN: xxx // setup via circleci
    working_directory: ~/repo

jobs:
  # Job for build
  build:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - save_cache:
          key: v1-dependencies-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - persist_to_workspace:
          root: ~/repo
          paths:
            - .

  # Job for test
  test:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: ~/repo
      - run:
          name: unit test
          command: yarn test
      - run:
          name: send coverage
          command: yarn codecov

workflows:
  per_commit:
    jobs:
      - build:
          name: build
          filters:
            branches:
              only: /.*/
      - test:
          name: test
          requires:
            - build
          filters:
            branches:
              only: /.*/
